name: All Branches
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install Arduino tools
        run: |
          pip install cpplint
      - name: Run C++ linter
        run: |
          cpplint --extensions=ino *.ino testing/anemometer/**/*.ino testing/sds011/**/*.ino

  test-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout custom WiFi library
        uses: actions/checkout@v2
        with:
          repository: skhg/home_wifi
          ref: master
          path: CustomHomeWiFiLibrary # must contain string "Custom"
      - name: Test compile for Arduino
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: esp8266:esp8266:nodemcu:xtal=80,vt=flash,ssl=all,eesz=4M2M,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200
          platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          required-libraries: ArduinoJson,Adafruit BME280 Library,Nova Fitness Sds dust sensors library
          sketch-names: "*.ino"
